name: middleman
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  repository_dispatch:
    types: build
jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: benchmark-driver/benchmark-driver.github.io
          ssh-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
          path: ./build
      - uses: actions/checkout@v2
        with:
          repository: benchmark-driver/sky2-result
          path: ../sky2-result

      - name: Install execjs runtime
        run: apt-get update && apt-get install -y nodejs
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3

      - name: middleman build
        run: bundle exec middleman build --verbose
        env:
          TZ: Asia/Tokyo
          RESULT_PATH: ../sky2-result

      - name: Deploy benchmark-driver.github.io
        run: |
          set -x
          cd ./build
          git add .
          if ! git diff-index --quiet HEAD --; then
            git config --global user.email "sky2-viewer@benchmark-driver.github.io"
            git config --global user.name "sky2-viewer"
            git commit -m "Automatic deployment by GitHub Actions

          Viewer: https://github.com/benchmark-driver/sky2-viewer/commit/$(git -C .. rev-parse HEAD)
          Result: https://github.com/benchmark-driver/sky2-result/commit/$(git -C ../../sky2-result rev-parse HEAD)"
            git push origin master
          fi
        if: github.ref == 'refs/heads/master'
