name: middleman
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.6
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
      - run: git clone --depth=1 git@github.com:benchmark-driver/benchmark-driver.github.io ./build
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      - run: git clone --depth=1 https://github.com/benchmark-driver/sky2-result ../sky2-result

      - name: Install execjs runtime
        run: apt-get update && apt-get install -y nodejs
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3

      - name: middleman build
        run: bundle exec middleman build --verbose
        env:
          TZ: Asia/Tokyo
          RESULT_PATH: ../sky2-result

      - name: Deploy benchmark-driver.github.io
        code: |
          set -x
          result_revision="$(git -C build rev-parse HEAD)"
          cd ../benchmark-driver.github.io
          git add .
          if ! git diff-index --quiet HEAD --; then
            git config --global user.email "sky2-result@benchmark-driver.github.io"
            git config --global user.name "sky2-result"
            git commit -m "Automatic deployment by GitHub Actions

          Viewer: https://github.com/benchmark-driver/sky2-viewer/commit/$(git rev-parse HEAD)
          Result: https://github.com/benchmark-driver/sky2-result/commit/$(git -C build rev-parse HEAD)"
            git push origin master
          fi
        # if: github.ref == 'refs/heads/master'
