name: middleman
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.7
    steps:
      - uses: actions/checkout@v2
      - name: Setup deploy key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh
      - run: git clone --depth=1 git@github.com:benchmark-driver/benchmark-driver.github.io ./build
      - run: git clone --depth=1 https://github.com/benchmark-driver/sky2-result ../sky2-result

      - name: Install execjs runtime
        run: apt-get update && apt-get install -y nodejs
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3

      - name: middleman build
        run: bundle exec middleman build --verbose
        env:
          TZ: Asia/Tokyo
          RESULT_PATH: ../sky2-result
