name: middleman
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:2.6
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
      - run: git clone --depth=1 git@github.com:benchmark-driver/benchmark-driver.github.io ./build
      - run: git clone --depth=1 https://github.com/benchmark-driver/sky2-result ../sky2-result

      - name: Install execjs runtime
        run: apt-get update && apt-get install -y nodejs
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3

      - name: middleman build
        run: bundle exec middleman build --verbose
        env:
          TZ: Asia/Tokyo
          RESULT_PATH: ../sky2-result
